/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbmsproject;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;  
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        goBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewData = new javax.swing.JButton();
        insertData = new javax.swing.JButton();
        updateData = new javax.swing.JButton();
        deleteData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showData = new javax.swing.JTable();
        b_idData = new javax.swing.JTextField();
        c_idData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnData = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pData = new javax.swing.JTextField();
        dData = new javax.swing.JTextField();
        p_idData = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        goBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        goBack.setText("<< Go Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Products");

        viewData.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewData.setForeground(new java.awt.Color(0, 204, 204));
        viewData.setText("View");
        viewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDataActionPerformed(evt);
            }
        });

        insertData.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        insertData.setForeground(new java.awt.Color(0, 204, 0));
        insertData.setText("Insert");
        insertData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDataActionPerformed(evt);
            }
        });

        updateData.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updateData.setForeground(new java.awt.Color(204, 204, 0));
        updateData.setText("Update");
        updateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataActionPerformed(evt);
            }
        });

        deleteData.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        deleteData.setForeground(new java.awt.Color(204, 51, 0));
        deleteData.setText("Delete");
        deleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataActionPerformed(evt);
            }
        });

        showData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Brand ID", "Category ID", "Last Name", "Price", "Desciption"
            }
        ));
        jScrollPane1.setViewportView(showData);

        b_idData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b_idData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_idDataActionPerformed(evt);
            }
        });

        c_idData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Brand ID        :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Category ID    :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Product Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Price               :");

        pnData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Description     :");

        pData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        dData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        p_idData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p_idData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_idDataActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Product ID     :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_idData)
                            .addComponent(c_idData)
                            .addComponent(pnData)
                            .addComponent(pData)
                            .addComponent(dData, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_idData, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(updateData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(insertData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(goBack))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(viewData)
                        .addGap(18, 18, 18)
                        .addComponent(insertData)
                        .addGap(18, 18, 18)
                        .addComponent(updateData)
                        .addGap(18, 18, 18)
                        .addComponent(deleteData)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_idData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(b_idData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_idData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        new Eintities().setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackActionPerformed

    private void viewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDataActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project_online_shoping","root","Abu@37011");
            Statement st = conn.createStatement();

            String sql = "SELECT * FROM products";
            ResultSet rs = st.executeQuery(sql);

            //////////////
            DefaultTableModel dm = (DefaultTableModel)showData.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged(); // notifies the JTable that the model has changed
            //////
            while(rs.next()){
                // Data will be added from start to end
                // Run while loop until all data is insert into the table
                String p_id = String.valueOf(rs.getInt("p_id"));
                String b_id = String.valueOf(rs.getInt("b_id"));
                String category_id = String.valueOf(rs.getInt("category_id"));
                String p_name = String.valueOf(rs.getString("p_name"));
                String price = String.valueOf(rs.getFloat("price"));
                String desc_ = String.valueOf(rs.getString("desc_"));

                // Array for Data
                String tbData[] = {p_id, b_id, category_id, p_name, price, desc_};
                DefaultTableModel tbModel = (DefaultTableModel)showData.getModel();

                // Add string array to the table
                tbModel.addRow(tbData);
            }

        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_viewDataActionPerformed

    private void insertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project_online_shoping","root","Abu@37011");
            String sql = "INSERT INTO products (b_id, category_id, p_name, price, desc_) VALUES (?,?,?,?,?)";
            PreparedStatement ptst = conn.prepareStatement(sql);
            ptst.setString(1,b_idData.getText());
            ptst.setString(2,c_idData.getText());
            ptst.setString(3,pnData.getText());
            ptst.setString(4,pData.getText());
            ptst.setString(5,dData.getText());
            ptst.executeUpdate();
            // ResultSet rs = st.executeQuery(sql);

            b_idData.setText("");
            c_idData.setText("");
            pnData.setText("");
            pData.setText("");
            dData.setText("");

            JOptionPane.showMessageDialog(this, "Successfully inserted data");

        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, "Insertion of data failed");
        }
    }//GEN-LAST:event_insertDataActionPerformed

    private void updateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project_online_shoping","root","Abu@37011");
            Statement st = conn.createStatement();
            /////////////
            if(!b_idData.getText().isEmpty()){
                st.execute("UPDATE products SET b_id = '" + b_idData.getText() + "' WHERE p_id = '" + p_idData.getText()+"'");
                b_idData.setText("");
            }
            if(!c_idData.getText().isEmpty()){
                st.execute("UPDATE products SET category_id = '" + c_idData.getText() + "' WHERE p_id = '" + p_idData.getText()+"'");
                c_idData.setText("");
            }
            if(!pnData.getText().isEmpty()){
//                st.execute("UPDATE customers SET middle_name = '" + pnData.getText() + "' WHERE c_id = '" + b_idData.getText()+"'");
                st.execute("UPDATE products SET p_name = '" + pnData.getText() + "' WHERE p_id = '" + p_idData.getText()+"'");
                pnData.setText("");
            }
            if(!pData.getText().isEmpty()){
                //st.execute("UPDATE customers SET last_name = '" + pData.getText() + "' WHERE c_id = '" + b_idData.getText()+"'");
                st.execute("UPDATE products SET price = '" + pData.getText() + "' WHERE p_id = '" + p_idData.getText()+"'");
                pData.setText("");
            }
            if(!dData.getText().isEmpty()){
                //st.execute("UPDATE customers SET c_address = '" + c_idData.getText() + "' WHERE c_id = '" + b_idData.getText()+"'");
                st.execute("UPDATE products SET desc_ = '" + dData.getText() + "' WHERE p_id = '" + p_idData.getText()+"'");
                dData.setText("");
            }
            p_idData.setText("");
            /////////////
            //            st.execute("UPDATE brands SET b_name = '" + fnData.getText() + "' WHERE b_id = '" + idData.getText()+"'");
            JOptionPane.showMessageDialog(null, "Successfully updated data");

        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, "Insertion of data failed");
        }
    }//GEN-LAST:event_updateDataActionPerformed

    private void deleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project_online_shoping","root","Abu@37011");
            Statement st = conn.createStatement();
            st.execute("DELETE FROM  products WHERE p_id = '" + p_idData.getText()+"'");
            b_idData.setText("");
            JOptionPane.showMessageDialog(null, "Successfully deleted data");

        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, "Insertion of data failed");
        }
    }//GEN-LAST:event_deleteDataActionPerformed

    private void b_idDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_idDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_idDataActionPerformed

    private void p_idDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_idDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_idDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Products().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_idData;
    private javax.swing.JTextField c_idData;
    private javax.swing.JTextField dData;
    private javax.swing.JButton deleteData;
    private javax.swing.JButton goBack;
    private javax.swing.JButton insertData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pData;
    private javax.swing.JTextField p_idData;
    private javax.swing.JTextField pnData;
    private javax.swing.JTable showData;
    private javax.swing.JButton updateData;
    private javax.swing.JButton viewData;
    // End of variables declaration//GEN-END:variables
}
